name: dyvolt
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  flutter_material_pickers: ^3.5.0
  barcode_widget: ^2.0.4
  table_calendar: ^3.0.9
  expandable: ^5.0.1
  video_player: ^2.6.1
  flutter_launcher_icons: ^0.13.1
  rive: ^0.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/payment/
    - assets/images/kurir/
    - assets/images/products/
    - assets/images/flight/logos/
    - assets/images/sliders/
    - assets/images/promo/
    - assets/animations/
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dyvolt_app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
  linux:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
